version: "2"

services:
  postgres:
    image: postgres:10-alpine
    volumes:
      - postgres-data/:/var/lib/postgresql/data/
      # - postgres-init-data/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=coc
      - POSTGRES_PASSWORD=coc@123
    #user: 1000
    ports:
      - "5432:5432"
    cpu_shares: 512
    mem_limit: 512M
    hostname: postgres
    domainname: coclab.lan
    #privileged: true
    #restart: always
    #stdin_open: true
    #tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"
volumes:
  postgres-data:
  # postgres-init-data: